- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC variabes
      include_vars: vars/vpc_setup
    - name: Create VProfile VPC
      ec2_vpc_net: 
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostname: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout