---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: no 
  tasks:
    - name: Import VPC setup variables
      include_vars: vars/output_vars

    - name: Import vprofile-setup variables
      include_vars: vars/vprostacksetup

    - name: 
        ec2_key:
          name: vprokey 
          region: "{{region}}"
        register: vprokey_out

    - name: Save Private key info to loginkey_vpro.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vprokey_out.changed

